### ISSUE TITLE
AES Cipher C_EncryptUpdate error

### ISSUE THREAD

**Issue by timdesi** [tpm2-software/tpm2-pkcs11#342] opened 2019-12-06 14:34 UTC
When i try to use AES Cipher from Java application have error below. This looks like an upstream error but i am not sure.

```
Cipher Provider : SunPKCS11-TPM2 version 13
PlainData : 6d7973656372657464617461
Key1 Algorithm : AES
update() failed
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:318:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000001d5) 
ERROR: Esys_EncryptDecrypt2: 0x1d5
java.security.ProviderException: update() failed
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Cipher.implUpdate(P11Cipher.java:629)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Cipher.engineUpdate(P11Cipher.java:526)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Cipher.engineDoFinal(P11Cipher.java:555)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Cipher.engineDoFinal(P11Cipher.java:541)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2208)
	at javaapplication4.JavaApplication4.main(JavaApplication4.java:134)
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_EncryptUpdate(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Cipher.implUpdate(P11Cipher.java:581)
	... 5 more
```

**Comment by williamcroberts** [comment] 2019-12-06 14:37
<snip>

> 
> Cipher Provider : SunPKCS11-TPM2 version 13 PlainData :
> 6d7973656372657464617461
> Key1 Algorithm : AES
> update() failed
> WARNING:esys:src/tss2-
> esys/api/Esys_EncryptDecrypt2.c:318:Esys_EncryptDecrypt2_Finish() Received
> TPM Error
> ERROR:esys:src/tss2-
> esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish
> ErrorCode (0x000001d5)
> ERROR: Esys_EncryptDecrypt2: 0x1d5

The error is:
tpm:parameter(1):structure is the wrong size

Paramter one is:
> TPM2B_MAX_BUFFER inData the data to be encrypted/decrypted

What size is the data you're trying to encrypt?


<snip>

**Comment by timdesi** [comment] 2019-12-06 14:49
PlainData : 6d7973656372657464617461 (mysecretdata)

**Comment by williamcroberts** [comment] 2019-12-08 21:40
This looks like a block size issue, what happens if you try to encrypt 16 bytes of data?

**Comment by williamcroberts** [comment] 2019-12-08 21:46
Also whats the mode? Can you reproduce in a test?

**Comment by williamcroberts** [comment] 2019-12-09 17:49
Can reproduce
```java
package tpm2;

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;
import java.security.KeyStore;
import java.security.KeyStore.PrivateKeyEntry;
import java.security.KeyStore.SecretKeyEntry;
import java.security.KeyStore.TrustedCertificateEntry;
import java.security.Provider;
import java.security.SecureRandom;
import java.security.Security;
import java.security.cert.X509Certificate;
import java.util.Enumeration;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.xml.bind.DatatypeConverter;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class PKCS11Test {

	@BeforeAll
	static void setUpBeforeClass() throws Exception {
		
	    String pkcs11Config = "name = SmartCard\nlibrary = /home/wcrobert/workspace/tpm2-pkcs11/src/.libs/libtpm2_pkcs11.so.0.0.0";
	    ByteArrayInputStream confStream = new ByteArrayInputStream(pkcs11Config.getBytes());
	    Provider prov = new sun.security.pkcs11.SunPKCS11(confStream);
	    Security.addProvider(prov);
	    KeyStore keyStore = null;
	    String pin = "myuserpin";
	    
	    SecretKey secretKey = null;
	    try {
	        keyStore = KeyStore.getInstance("PKCS11",prov);
	        KeyStore.PasswordProtection pp = new KeyStore.PasswordProtection(pin.toCharArray());
	        keyStore.load(null ,  pp.getPassword());
	        
        
	        Enumeration<String> aliases = keyStore.aliases();
	        while (aliases.hasMoreElements()) {
	            String alias = aliases.nextElement();
	            
	            KeyStore.Entry obj = keyStore.getEntry(alias.toString(), null);
	            if (obj instanceof SecretKeyEntry) {
	            	secretKey = (SecretKey)keyStore.getKey(alias.toString(), null);
	            }
	            try {
	                System.out.println(obj);
	            } catch (Exception e) {
	    	        e.printStackTrace();
	            	continue;
	            }
	        }
	    } catch (Exception e) {
	    	System.out.println(e);
	        e.printStackTrace();
	    }
		
//	    SecureRandom secureRandom = new SecureRandom();
//	    byte[] iv = new byte[12];
//		secureRandom.nextBytes(iv);
	    
	    byte [] plaintext = DatatypeConverter.parseHexBinary("6d7973656372657464617461");
	    
		final Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING");
		cipher.init(Cipher.ENCRYPT_MODE, secretKey);
		
		byte [] ciphertext = cipher.doFinal(plaintext);
	    

		cipher.init(Cipher.DECRYPT_MODE, secretKey);
		byte[] decplaintext = cipher.doFinal(ciphertext);

		System.out.println(DatatypeConverter.printHexBinary(decplaintext));
	}

	@Test
	void test() {
		fail("Not yet implemented");
	}

}
```

**Comment by williamcroberts** [comment] 2019-12-09 18:30
There seems to be an issue with Java. On my System, running with OpenJDK8, the padding argument isn't respected and it always defaults to CKA_AES_CBC mode. It needs to be CKM_AES_CBC_PAD if you want to use non-block size input data. However, we don't support that mode internally yet, so it would fail there instead. The below code, on block size does work:

```java
Cipher cipher = Cipher.getInstance("AES/CBC/NOPADDING");
    	
byte [] plaintext = DatatypeConverter.parseHexBinary("6d7973656372657464617461aabbccdd");
		    	    
cipher.init(Cipher.ENCRYPT_MODE, secretKey);
			
AlgorithmParameters params = cipher.getParameters();

byte[] iv = params.getParameterSpec(IvParameterSpec.class).getIV();

byte [] ciphertext = cipher.doFinal(plaintext);
		    
cipher.init(Cipher.DECRYPT_MODE, secretKey, new IvParameterSpec(iv));
byte[] decplaintext = cipher.doFinal(ciphertext);

System.out.println(DatatypeConverter.printHexBinary(decplaintext));
```
You could apply PKCS5 or PKCS7 padding by hand and then call the routine.

This doesn't appear to be our bug, closing.

**Closed by williamcroberts** 2019-12-09 18:30 UTC
Labels: bug, in-progress
