### ISSUE TITLE
C_SignInit breaks for re-authentication

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#169] opened 2019-03-20 11:42 UTC
Hi,
I'm not 100% sure - but if I understand correctly, C_SignInit must not break the initialization if a (re-)login is required.

"Re-authentication occurs by calling C_Login with userType set to CKU_CONTEXT_SPECIFIC immediately after a cryptographic operation using the key has been initiated (e.g. after C_SignInit). In this call, the actual user type is implicitly given by the usage requirements of the active key. If C_Login returns CKR_OK the user was successfully authenticated and this sets the active key in an authenticated state that lasts until the cryptographic operation has successfully or unsuccessfully been completed (e.g. by C_Sign, C_SignFinal,..)." (http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959719)

Current implementation breaks the C_SignInit returns CKR_USER_NOT_LOGGED_IN

**Comment by williamcroberts** [comment] 2019-03-20 17:34
So this flow:
C_SignInit()
C_Login(CKU_CONTEXT_SPECIFIC)
C_Sign()
(implicit C_Logout())

**Comment by PeterHuewe** [comment] 2019-03-20 19:19
This flow would be what I need ;)

**Comment by williamcroberts** [comment] 2019-11-07 15:36
@PeterHuewe doesn't this require attribute CKA_ALWAYS_AUTHENTICATE to be true?

**Comment by PeterHuewe** [comment] 2019-11-07 16:50
Yes, and this attribute is expected from my application

**Comment by williamcroberts** [comment] 2019-11-08 17:50
So #170 is really a duplicate of this, so I have to add support for that. Closeing #170 as a dup.

**Closed** 2019-11-12 14:11 UTC
Labels: in-progress
