### ISSUE TITLE
Spurious errors encrypting and decrypting with AES key using Python

### ISSUE THREAD

**Issue by bnevis-i** [tpm2-software/tpm2-pkcs11#566] opened 2020-07-30 15:18 UTC
## Environment

Board: APL UPSquared with PTT
OS: Ubuntu 20.04 (opensc 0.20.0-3)
tpm2-tss: 4.2.1 (tarball)
tpm2-pkcs11: 1.3.1 (tarball)
tpm2-tools: 4.1.3 (tarball)
tpm2-abrmd: Not installed
Token initialized with tpm2_ptool with label tpmhsm

AES key generated with
`tpm2_ptool addkey --id  (someid) --userpin (redacted) --algorithm aes128 --label tpmhsm --key-label aeskey`

## Script
```
import os
import pkcs11

lib = pkcs11.lib('libtpm2_pkcs11.so')

token = lib.get_token(token_label='tpmhsm')

with token.open(rw=False, user_pin='123456') as session:
    print(session)
    key = session.get_key(label='aeskey')
    print(key)

    iv = session.generate_random(128)
    plaintext = '1234567890123456'
    ciphertext = key.encrypt(plaintext, mechanism=pkcs11.mechanisms.Mechanism.AES_CBC, mechanism_param=iv)
    print(ciphertext)
    plaintext = 'notdecrypted'
    plaintext = key.decrypt(ciphertext, mechanism=pkcs11.mechanisms.Mechanism.AES_CBC, mechanism_param=iv)
    print(plaintext)
```

## Error message
```
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
<pkcs11._pkcs11.Session object at 0x7f357ca04e50>
<SecretKey label='aeskey' id='3133333239303338326537393434343839393866386238316661346132373732' 128-bit AES>
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:318:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000b0143) 
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:318:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000b0143) 
b'\xdb\xdc\x93\x9b]A\xdb\xc5\xa4 \x11\x82\x7f!-\n'
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:318:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000b0143) 
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:318:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000b0143) 
b'1234567890123456'
```

Encryption and decryption appear to work despite errors logged to console.

**Comment by williamcroberts** [comment] 2020-07-30 19:19
Duplicat of https://github.com/tpm2-software/tpm2-pkcs11/issues/515, just update your tss version past tpm2-software/tpm2-tss@6eb5a49

The only release that has it is RC0 and RC1 of 3.0 of the tpm2-tss project.

**Comment by williamcroberts** [comment] 2020-07-30 19:44
Per @tstruk fixed on tpm2-tss 2.4.2

**Comment by bnevis-i** [comment] 2020-07-30 21:46
Not convinced this is fixed.

building from tss 2.4.x branch (commit 83043f308b86b607f1c326fd4afad6ae0b43c492)

```
<pkcs11._pkcs11.Session object at 0x7f00a5c5f9d0>
<SecretKey label='aeskey' id='3133333239303338326537393434343839393866386238316661346132373732' 128-bit AES>
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:322:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000b0143) 
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:322:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000b0143) 
b"\xe5\xa98\xe3U\xea'\xc7\xc3-<MC\xa7\x89\x0f"
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:322:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000b0143) 
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:322:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000b0143) 
b'1234567890123456'
```

**Comment by tstruk** [comment] 2020-07-30 22:22
The spurious errors is fixed for only Esys_TestParms(). With Esys_EncryptDecrypt2() the problem is that your HW doesn't support it and returns "command code not supported" (0x000b0143). We can not fix this in TSS.

**Comment by bnevis-i** [comment] 2020-07-30 22:24
How do you explain that encryption and decryption actually appeared to work?

**Comment by tstruk** [comment] 2020-07-30 22:37
Actually this error code was returned not by the HW, but by the resource manager. That would explain why it worked.
What version of abrmd are you running?

**Comment by bnevis-i** [comment] 2020-07-30 22:39
Kernel resource manager (/dev/tpmrm0)

**Comment by tstruk** [comment] 2020-07-30 22:53
So that couldn't possibly work as the requests wasn't event sent to the HW.
Maybe there is a fallback in the upper layer of PCKS11 stack?

**Comment by bnevis-i** [comment] 2020-07-30 23:27
Not sure, but #557 would provide an independent way to test this by trying to decrypt known ciphertext with a known key.

**Comment by williamcroberts** [comment] 2020-07-31 15:14
> How do you explain that encryption and decryption actually appeared to work?

We fall back to the original interface:
https://github.com/tpm2-software/tpm2-pkcs11/blob/master/src/lib/tpm.c#L1794

I guess I could run getcap command on pkcs11 initialization and verify that this command is supported before trying it.

**Comment by williamcroberts** [comment] 2020-07-31 15:16
@tstruk I would love a silence option to the TSS, since it reports stuff to stderr that applications might not want.

**Comment by tstruk** [comment] 2020-07-31 16:34
> @tstruk I would love a silence option to the TSS, since it reports stuff to stderr that applications might not want.

./configure --with-maxloglevel=none should silence everything. You may also set TSS2_LOG="all+NONE" in runtime to do the same trick.

**Comment by williamcroberts** [comment] 2020-07-31 17:10
> ./configure --with-maxloglevel=none should silence everything. You may also set TSS2_LOG="all+NONE" in runtime to do the same trick.

```TSS2_LOG="all+NONE"```
@tstruk thanks!  I was looking for that!
Is their any writeup with examples on this? I searched for how to configure this stuff and never saw anything I could grok.

**Comment by tstruk** [comment] 2020-07-31 17:34
> `TSS2_LOG="all+NONE"`
> @tstruk thanks! I was looking for that!
> Is their any writeup with examples on this? I searched for how to configure this stuff and never saw anything I could grok.

https://github.com/tpm2-software/tpm2-tss/blob/master/doc/logging.md

**Closed** 2020-08-03 16:21 UTC
